[Server]
ListenAddress = "127.0.0.1"
ListenPort = 8080

[Database]
Host = "127.0.0.1"
Port = 5432
Name = "runciv"
User = "runciv"
Password = "super-secure-password"

[Logging]
LogLevel = "info"
Path = "/var/log/runciv/main.log"
RotationFileSize = "10 MB"
MaxRotationCount = 10

[[Logging.AdditionalFileLoggers]]
Name = "requests"
AddToMainLogger = true
Path = "/var/log/runciv/requests.log"
RotationFileSize = "10 MB"
MaxRotationCount = 5
AlternativePattern = "{h([{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5}])} {m}{n}"
