[Migration]
Hash = '2697429211545730140'
Initial = false
Dependency = 1
Replaces = []

[[Migration.Operations]]
Type = 'CreateModel'
Name = 'friend'

[[Migration.Operations.Fields]]
Name = 'id'
Type = 'int64'

[[Migration.Operations.Fields.Annotations]]
Type = 'auto_increment'

[[Migration.Operations.Fields.Annotations]]
Type = 'primary_key'

[[Migration.Operations.Fields]]
Name = 'is_request'
Type = 'boolean'

[[Migration.Operations.Fields.Annotations]]
Type = 'not_null'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'friend'

[Migration.Operations.Field]
Name = 'from'
Type = 'varbinary'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'account'
ColumnName = 'uuid'
OnDelete = 'Cascade'
OnUpdate = 'Cascade'

[[Migration.Operations]]
Type = 'CreateField'
Model = 'friend'

[Migration.Operations.Field]
Name = 'to'
Type = 'varbinary'

[[Migration.Operations.Field.Annotations]]
Type = 'not_null'

[[Migration.Operations.Field.Annotations]]
Type = 'foreign_key'

[Migration.Operations.Field.Annotations.Value]
TableName = 'account'
ColumnName = 'uuid'
OnDelete = 'Cascade'
OnUpdate = 'Cascade'
